export const LOAD_BOOKS = "LOAD_BOOKS";
export const SET_BOOKS = "SET_BOOKS";
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const LOAD_SEARCHED_BOOKS = 'LOAD_SEARCHED_BOOKS';
export const SET_ACTIVE_BOOK_ID = 'SET_ACTIVE_BOOK_ID'
export const SET_ACTIVE_BOOK = 'SET_ACTIVE_BOOK'