export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE';

export const SET_COUNT_TOTAL = 'SET_COUNT_TOTAL';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'